- name: Set sysctl settings
  sysctl: name="{{ item }}" value="{{ sysctl_set[item] }}"
  with_items: "{{ sysctl_set.keys() }}"
- name: Ensure hostname is resolvable
  shell: ping -c1 $(hostname --fqdn)
- name: Install eucalyptus-nc
  yum: name=eucalyptus-nc
- name: Load bridge module
  modprobe: name=bridge
- shell: tuned-adm profile virtual-host
- copy: src=templates/keys/{{ item }} dest=/var/lib/eucalyptus/keys/
  with_items:
  - cloud-cert.pem
  - "{{ azone }}/cluster-cert.pem"
  - "{{ azone }}/cluster-pk.pem"
  - "{{ azone }}/node-cert.pem"
  - "{{ azone }}/node-pk.pem"
  when: azone is defined
- service: name={{ item }} state=restarted enabled=yes
  with_items:
  - libvirtd
  - messagebus
- service: name=eucalyptus-nc state=restarted enabled=yes
  when: ansible_distribution_version < "7"
- service: name=eucalyptus-node state=restarted enabled=yes
  when: ansible_distribution_version >= "7"
- name: Delete virtual network interface
  shell: virsh net-destroy default; virsh net-autostart default --disable
  ignore_errors: true
- wait_for: port=8775
