- name: Copy hosts file
  copy: src=templates/hosts_file dest=/etc/hosts owner=root group=root mode=0644
- name: Set hostname
  hostname: name={{ inventory_hostname }}
- name: Install packages
  yum: name={{ item }}
  with_items:
  - libselinux-python
  - ntp
  - tuned
  - http://downloads.eucalyptus.com/software/eucalyptus/4.2/centos/6/x86_64/eucalyptus-release-4.2-1.el6.noarch.rpm
  - http://downloads.eucalyptus.com/software/euca2ools/3.3/centos/6/x86_64/euca2ools-release-3.3-1.el6.noarch.rpm
  - http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
  register: repo_added
- name: Enable rhel-6-server-optional-rpms repo
  shell: subscription-manager repos --enable=rhel-6-server-optional-rpms
  when: ansible_distribution == 'Red Hat Enterprise Linux'
- name: Install midokura repo
  copy: src=templates/repo/midokura.repo dest=/etc/yum.repos.d/midokura.repo
- name: Update packages
  yum: name=* state=latest
  when: repo_added|changed
- name: Set selinux to permissive
  selinux: policy=targeted state=permissive
- name: Start ntp
  service: name=ntpd state=restarted enabled=yes pattern='/ntpd'
- name: Create eucalyptus directory
  file: path=/etc/eucalytpus state=directory
- name: Copy eucalyptus.conf
  template: src=templates/eucalyptus/eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf owner=root group=root mode=0644

#- file: path=/etc/sysconfig/network-scripts/ifcfg-* state=absent
###########################
# Set INTERNAL networking
###########################
- template: src=templates/network-scripts/ifcfg-lo.j2 dest=/etc/sysconfig/network-scripts/ifcfg-lo
- template: src=templates/network-scripts/ifcfg-eth.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth0

- block:
  # Set internal bridge config file on NCs
  - template: src=templates/network-scripts/ifcfg-br.j2 dest=/etc/sysconfig/network-scripts/ifcfg-br0
  - shell: brctl setfd br0 2 && brctl sethello br0 2 && brctl stp br0 off
  when: "'nc' in group_names"

###########################
# Set EXTERNAL networking
###########################
- block:
  - name: Networking - External - load modules
    modprobe: name=bonding
  - name: Networking - External - Copy sysconfig ifcfg files
    template: src=templates/network-scripts/ifcfg-bond.j2 dest=/etc/sysconfig/network-scripts/ifcfg-bond0
  - name: Networking - External - Set bonded slave interfaces
    template: src=templates/network-scripts/ifcfg-eth.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item }}
    with_items: "{{ ext_bond_slaves }}"
  # - name: Networking - External - Remove internal gateway if ext - eth0
  #   lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0 regexp=^GATEWAY line=""
  when: ext is defined

###########################
# Other
###########################
# - name: Networking - Find ifcfg files
#   find: paths="/etc/sysconfig/network-scripts" patterns="ifcfg-*"
#   register: result
# - name: Networking - Disable NetworkManager on all interfaces
#   lineinfile: dest={{ item.path }} regexp=^NM_CONTROLLED line="NM_CONTROLLED=no"
#   with_items: "{{ result.files }}"
- name: Networking - Create iptables firewall rules
  template: src=templates/iptables_rules.j2 dest=/etc/sysconfig/iptables
- name: Reload firewall rules from file
  shell: iptables-restore < /etc/sysconfig/iptables
- name: Restart iptables
  service: name=iptables state=restarted enabled=yes
- name: Restart networking
  service: name=network state=restarted enabled=yes
